SELECT 'Olá, bem vindo ao SQL!';
SELECT 10;
SELECT now();
SELECT 20 * 2;
SELECT 50/2;
SELECT 18 AS idade;
SELECT 2019 AS ano;
SELECT 'Rafael', 'Martins', 25, 'Desenvolvedor Web';
SELECT 'Guilherme' AS nome, 'Gomes' AS sobrenome, 31 AS idade, 'Belo Horizonte' AS 'Cidade Natal';
SELECT 'Guilherme' AS nome;
SELECT 13 * 8;
SELECT now() AS 'Data Atual';
SELECT * FROM sakila.actor;
SELECT CONCAT (first_name, last_name) FROM sakila.actor;
SELECT CONCAT (first_name, ' ', last_name) FROM sakila.actor;
SELECT CONCAT (first_name, ' ', last_name) AS 'Nome Completo' FROM sakila.actor;
SELECT * FROM sakila.film;
SELECT CONCAT (title, ' - ', release_year) AS 'Lancamento do Filme' FROM sakila.film;
SELECT CONCAT (title, ' - ', rating) AS Classificacao FROM sakila.film;
SELECT * FROM sakila.address;
SELECT CONCAT (address, ' - ', district) AS Endereco FROM sakila.address;
